### ISSUE TITLE
Node metrics

### ISSUE THREAD

**Issue by mihai-sysbio** [elixir-europe-training/Training-Metrics-Database#1]
**User stories**
As a Training Coordinator, I want to see the metrics for my node (only), so that I can use that in funding applications and reports, and improve quality of training in my node.
As a Training coordinator, I want to see the detailed view of each metric type (quality, demographics, impact) for each event separately, so that I can make sure they correspond with the data that has been gathered.

**Sub-stories**
- [x] As a user, I can log in with username/email and password.
- [x] I am recognized as an authorized user (such as Training Coordinator) for my node.
- [x] I can see ELIXIR-wide metrics (for which no login is required).
- [x] I can see node-specific metrics (for my node only) for all training events.
- [x] I can see node-specific metrics (for my node only) for a single training event at a time, for a single metric type at a time.
- [ ] The node-specific metrics charts/tables that I see are the same as for the ELIXIR-wide metrics, but based only on my Node's data.
- [ ] I can export node-specific data for charts (for my node only) in CSV/Excel format.
- [x] I can log out.

**Comment by ninanorgren** [comment]
Check that the login functionality still works, there seem to be some issues

**Comment by mihai-sysbio** [comment]
> Check that the login functionality still works, there seem to be some issues

Logging in works fine for me, for credentials see the `users.csv` file on the VM.
